POST http://localhost:6000/register
Content-Type: application/json

{
  "username": "david",
  "name": "david miller",
  "password": "the_miller@23",
  "gender": "male",
  "location": "bangalore"
}

###

POST http://localhost:6000/login
Content-Type: application/json

{
  "username": "david",
  "password": "the_miller@23"
}


###


POST http://localhost:6000/users/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkIiwiaWF0IjoxNjM5MTQyNzc3fQ.lKAS0Kk7v-mcnAlejcPQA41e7oEX_CqzL27-UnZm2P8


###
