POST http://localhost:6000/register
Content-Type: application/json

{
  "username": "david",
  "name": "david miller",
  "password": "the_miller@23",
  "gender": "male",
  "location": "bangalore"
}

###

POST http://localhost:6000/login
Content-Type: application/json

{
  "username": "david",
  "password": "the_miller@23"
}


###


POST http://localhost:6000/users/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkIiwiaWF0IjoxNjM5MTUwMTU2fQ.B-7sFngWn0cvqAhj-ahjan25MQOqlVubOBJX8t1SA_c


###

GET http://localhost:6000/users/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRhdmlkIiwiaWF0IjoxNjM5MTUwMTU2fQ.B-7sFngWn0cvqAhj-ahjan25MQOqlVubOBJX8t1SA_c

###